
[functions.scan-receipt]
enabled = true
verify_jwt = false
import_map = "./functions/scan-receipt/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/scan-receipt/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/scan-receipt/*.html" ]

[functions.scan-love-list]
enabled = true
verify_jwt = false
import_map = "./functions/scan-love-list/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/scan-love-list/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/scan-love-list/*.html" ]

[functions.translate-task]
enabled = true
verify_jwt = false
import_map = "./functions/translate-task/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/translate-task/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/translate-task/*.html" ]

[functions.notify-suggestion]
enabled = true
verify_jwt = false
entrypoint = "./functions/notify-suggestion/index.ts"

[functions.rapid-handler]
enabled = true
verify_jwt = false
entrypoint = "./functions/rapid-handler/scan-job-sheet.ts"
